import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Button } from "../Components/Button";
import GibbsRule from "../Components/GibbsRule";
import { gibbsRules } from "../Data/GibbsRules";

const Gibbs: NextPage = (props) => {
  const [currentRuleIndex, setCurrentRuleIndex] = useState<number>(0);

  const previousRule = () => {
    if (currentRuleIndex <= 0) {
      return;
    }

    setCurrentRuleIndex(currentRuleIndex - 1);
  };

  const nextRule = () => {
    if (currentRuleIndex === gibbsRules.length - 1) {
      return;
    }

    setCurrentRuleIndex(currentRuleIndex + 1);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>Gibbs Rules</h1>
      </header>

      <main>
        <GibbsRule ruleInfo={gibbsRules[currentRuleIndex]} />
      </main>

      <Button mode="accept" onClick={previousRule}>
        Previous
      </Button>
      <Button mode="accept" onClick={nextRule}>
        Next
      </Button>
    </div>
  );
};

export default Gibbs;
