import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Button } from "../Components/Button";
import GibbsRule from "../Components/GibbsRule";
import { NavBar } from "../Components/NavBar";
import { gibbsRules } from "../Data/QuoteArrays/GibbsRules";

const Gibbs: NextPage = () => {
  const [currentRuleIndex, setCurrentRuleIndex] = useState<number>(0);

  const previousDisabled = currentRuleIndex <= 0;
  const nextDisabled = currentRuleIndex >= gibbsRules.length - 1;

  const previousRule = () => {
    if (!previousDisabled) {
      setCurrentRuleIndex(currentRuleIndex - 1);
    }
  };

  const nextRule = () => {
    if (!nextDisabled) {
      setCurrentRuleIndex(currentRuleIndex + 1);
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main>
        <GibbsRule ruleInfo={gibbsRules[currentRuleIndex]} />
      </main>

      <Button mode="default" disabled={previousDisabled} onClick={previousRule}>
        Previous
      </Button>

      <Button mode="default" disabled={nextDisabled} onClick={nextRule}>
        Next
      </Button>
    </div>
  );
};

export default Gibbs;
