import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { NavBar } from "../Components/NavBar";
import Conversation, { ConversationTemplate } from "../Components/Conversation";
import { getDeterministicArrayItems } from "../Helpers/DeterministicSeeding";
import { DailyCharactersInfo, Person } from "../Data/PersonMappings";
import Settings from "../Components/Settings";
import { useState } from "react";

/** Model of the properties of the component */
type HomePageProps = {
  dailyQuotes: { person: Person; conversation: ConversationTemplate }[];
};

/**
 * Server-side renders the properties of the component.
 * @returns Properties of the component.
 */
export const getServerSideProps: GetServerSideProps<HomePageProps> = async () => {
  // Get the daily quote for each character
  const dailyQuotes = DailyCharactersInfo.map((characterInfo) => ({
    person: characterInfo.person,
    conversation: getDeterministicArrayItems(1, characterInfo.array)[0],
  }));

  return { props: { dailyQuotes: dailyQuotes } };
};

/**
 * Renders the home page.
 * @param props Properties of the home page.
 * @returns The home page.
 */
const Home: NextPage<HomePageProps> = (props) => {
  const [selectedCharacters, setSelectedCharacters] = useState<Person[]>(
    // By default, all characters are shown
    DailyCharactersInfo.map((character) => character.person)
  );

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Settings selectedCharacters={selectedCharacters} setSelectedCharacters={setSelectedCharacters} />

      <main>
        {props.dailyQuotes
          .filter((quote) => selectedCharacters.includes(quote.person))
          .map((dailyQuote, index) => {
            // Display the daily quote of each character
            return <Conversation key={index} conversation={dailyQuote.conversation} />;
          })}
      </main>
    </div>
  );
};

export default Home;
