import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import GibbsRule from "../Components/GibbsRule";
import ZivaMisquote from "../Components/ZivaMisquote";
import { gibbsRules, GibbsRuleTemplate } from "../Data/GibbsRules";
import { tonyJokes } from "../Data/TonyJokes";
import { zivaMisquotes, ZivaMisquoteTemplate } from "../Data/ZivaMisquotes";
import { getDeterministicArrayItems } from "../Helpers/DeterministicSeeding";

/** Model of the properties of the component */
type HomePageProps = { dailyGibbsRule: GibbsRuleTemplate, dailyZivaMisquote: ZivaMisquoteTemplate }

/**
 * Server-side renders the properties of the component.
 * @returns Properties of the component.
 */
export const getServerSideProps: GetServerSideProps<HomePageProps> = async () => {
  const dailyGibbsRule = getDeterministicArrayItems(1, gibbsRules)[0];
  const dailyZivaMisquote = getDeterministicArrayItems(1, zivaMisquotes)[0];

  return { props: { dailyGibbsRule, dailyZivaMisquote } }
}

/**
 * Renders the home page.
 * @param props Properties of the home page.
 * @returns The home page.
 */
const Home: NextPage<HomePageProps> = (props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>Gibbs Rules</h1>
      </header>

      <main>
        <GibbsRule ruleInfo={props.dailyGibbsRule} />
        {/* <ZivaMisquote misquoteInfo={props.dailyZivaMisquote} /> */}
      </main>
    </div>
  );
}

export default Home;
